#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "46i \\\n\tlocation /redirect_me {\n\t\t return 301 https://github.com/kamalinux;\n\t}\n" /etc/nginx/sites-available/default # Line 46
sudo service nginx start
