#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "27i \\\n\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx reload
