#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
# We can use IFS before read command and set to NULL to prevents
# leading or trailing whitespace from being trimmed.

while read -r line;
do
	echo "$line" | cut -d ':' -f 1,3,6
done < "/etc/passwd"
