#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=':' read -r username password userID groupID userINFO home shell;
do
  echo "The user $username is part of the $groupID gang,"\
  "lives in $home and rides $shell."\
  "$userID's place is protected by the passcode $password,"\
  "more info about the user here: $userINFO"
done < "/etc/passwd"
