#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.
# We can use | sort | uniq -c to sort the output

awk '{ print $1 " " $9}' apache-access.log
